### PR TITLE
save mobile users

### PR DESCRIPTION
**Pull request by ohlookitsderpy**
ken pls that WAV is going to destroy mobile data

also send unblock pls

### CODE REVIEW

**Comment by tonkku107** [comment]
get unlimited u pleb

**Comment by ohlookitsderpy** [comment]
stfu tonkku data is expensive :cry:

**Comment by tonkku107** [comment]
not here

**Comment by Luke-6723** [comment]
Its the same in the UK, Too expensive 4 me

**Comment by ohlookitsderpy** [comment]
im in the uk

**Pull request merged**
